name: Go

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build chat-microservice
        run: |
          cd chat-microservice
          go mod tidy
          go build -v ./...

      - name: Lint chat-microservice
        run: |
            cd chat-microservice
            golangci-lint-action@v4 --version latest --args "--config=.golangci.yaml"

      - name: Test chat-microservice
        run: |
          cd chat-microservice
          go mod tidy
          go test -v -race -coverpkg=./... ./...

      - name: Build storage-microservice
        run: |
          cd storage-microservice
          go mod tidy
          go build -v ./...

      - name: Lint storage-microservice
        run: |
            cd chat-microservice
            golangci-lint-action@v4 --version latest --args "--config=.golangci.yaml"


      - name: Test storage-microservice
        run: |
          cd storage-microservice
          go mod tidy
          go test -v -race -coverpkg=./... ./...
